const state = {
    ENTER_AMOUNT_SGD: 'ENTER_AMOUNT_SGD',
    ENTER_DESCRIPTION: 'ENTER_DESCRIPTION',
    ENTER_CATEGORY: 'ENTER_CATEGORY',
    DELETE_PREVIOUS_EXPENSE: 'DELETE_PREVIOUS_EXPENSE',
    START: 'START',
    ENTER_EXCHANGE_RATE: 'ENTER_EXCHANGE_RATE',
    ENTER_TRIP_NAME: 'ENTER_TRIP_NAME',
    ENTER_AMOUNT_OVERSEAS: 'ENTER_AMOUNT_OVERSEAS'
}

module.exports = state
