const state = {
    ENTER_AMOUNT_SGD: 'ENTER_AMOUNT_SGD',
    ENTER_DESCRIPTION: 'ENTER_DESCRIPTION',
    ENTER_CATEGORY: 'ENTER_CATEGORY',
    DELETE_PREVIOUS_EXPENSE: 'DELETE_PREVIOUS_EXPENSE',
    START: 'START'
}

module.exports = state
